import { ThemeTokens } from "./quizEdit.types";

export const THEMES: Record<"dark" | "light", ThemeTokens> = {
  dark: {
    pageBg: "var(--clr-bg)",
    topbarBg: "var(--clr-surface)",
    cardBg: "var(--clr-surface)",
    cardBorder: "var(--clr-border)",
    inputBg: "var(--clr-surface2)",
    inputBorder: "var(--clr-border2)",
    inputText: "var(--clr-text)",
    inputPlaceholder: "var(--clr-text3)",
    labelColor: "var(--clr-text2)",
    headingColor: "var(--clr-text)",
    subText: "var(--clr-text2)",
    divider: "var(--clr-border)",
    toggleBg: "var(--clr-surface2)",
    toggleBorder: "var(--clr-border2)",
    toggleActiveBg: "var(--clr-accent3)",
    toggleActiveText: "var(--clr-accent)",
    toggleInactiveText: "var(--clr-text3)",
    badgeBg: "var(--clr-surface2)",
    badgeBorder: "var(--clr-border2)",
    badgeText: "var(--clr-text3)",
    sectionLabel: "var(--clr-text2)",
    qPillBg: "var(--clr-surface2)",
    qPillBorder: "var(--clr-border2)",
    qPillText: "var(--clr-text3)",
    deleteBg: "var(--clr-surface2)",
    deleteText: "var(--clr-text3)",
  },
  light: {
    pageBg: "var(--clr-bg)",
    topbarBg: "var(--clr-surface)",
    cardBg: "var(--clr-surface)",
    cardBorder: "var(--clr-border)",
    inputBg: "var(--clr-surface2)",
    inputBorder: "var(--clr-border2)",
    inputText: "var(--clr-text)",
    inputPlaceholder: "var(--clr-text3)",
    labelColor: "var(--clr-text2)",
    headingColor: "var(--clr-text)",
    subText: "var(--clr-text2)",
    divider: "var(--clr-border)",
    toggleBg: "var(--clr-surface2)",
    toggleBorder: "var(--clr-border2)",
    toggleActiveBg: "var(--clr-accent3)",
    toggleActiveText: "var(--clr-accent)",
    toggleInactiveText: "var(--clr-text3)",
    badgeBg: "var(--clr-surface2)",
    badgeBorder: "var(--clr-border2)",
    badgeText: "var(--clr-text3)",
    sectionLabel: "var(--clr-text2)",
    qPillBg: "var(--clr-surface2)",
    qPillBorder: "var(--clr-border2)",
    qPillText: "var(--clr-text3)",
    deleteBg: "var(--clr-surface2)",
    deleteText: "var(--clr-text3)",
  },
};